package templates

import "github.com/MakeNowJust/heredoc"

// CommandVersionTemplate is the template for the CLI version output.
var CommandVersionTemplate = heredoc.Doc(`
	chart-releaser:
	  version:      {{ .Version }}
	  build date:   {{ .BuildDate }}
	  commit:       {{ .Commit }}
	  tag:          {{ .Tag }}
	  go version:   {{ .GoVersion }}
	  go compiler:  {{ .Compiler }}
	  platform:     {{ .OS }}/{{ .Arch }}
`)

// FlagLatestVersionTemplate is the template for the output when the --latest flag is specified.
var FlagLatestVersionTemplate = heredoc.Doc(`

	{{ .Status }}

	latest:    {{ .Latest }}
	installed: {{ .Installed }}
`)

// ConfigFileTemplate is the template used to generate a new basic configuration file for
// chart-releaser from the `init` command.
var ConfigFileTemplate = heredoc.Doc(`
	{{ .Header }}
	version: v1
	chart:
	  name: {{ .Chart }}
      {{- if .Path }}path: {{ .Path }}{{ end }}
      repo: github.com/{{ .GithubOwner }}/{{ .GithubName }}
	commit:
	  author:
	    name: {{ .AuthorName }}
	    email: {{ .Author.Email }}
`)

// ConfigHeaderComment is the header comment which is applied to the generated config file.
var ConfigHeaderComment = heredoc.Doc(`
	# .chartreleaser.yaml is the configuration file for chart-releaser, a CI tool
	# to update Helm Charts on application release. See the documentation at
	# https://github.com/edaniszewski/chart-releaser
	
`)

// DefaultUpdateCommitMessage is the default template for a commit message used when
// updating a file.
var DefaultUpdateCommitMessage = `[{{ .Chart.Name }}] bump chart to {{ .Chart.NewVersion }} for new application release ({{ .App.NewVersion }})`

// DefaultPullRequestTitle is a template for the default title used when opening a pull
// request for the updates generated by chart-releaser.
//
// This is only used when the configuration specifies that a pull request should be
// opened after committing any updates.
var DefaultPullRequestTitle = `Bump {{ .Chart.Name }} Chart from {{ .Chart.PreviousVersion }} to {{ .Chart.NewVersion }}`

// DefaultPullRequestBody is a template for the default comment used when opening
// a new pull request, summarizing the changes.
//
// This is only used when the configuration specifies that a pull request should be
// opened after committing any updates.
var DefaultPullRequestBody = heredoc.Doc(`
	Bumps the {{ .Chart.Name }} Helm Chart from {{ .Chart.PreviousVersion }} to {{ .Chart.NewVersion }}.

	{{ if .Files }}The following files have also been updated:
	{{ range .Files }}- {{ .Path }}
	{{ end }}{{ end }}
	---
	*This PR was generated with [chart-releaser](https://github.com/edaniszewski/chart-releaser)*
`)

// DefaultBranchName is a template specifying the default name of the branch to create
// when updating under the "pull request" strategy.
var DefaultBranchName = `chartreleaser/{{ .Chart.Name }}/{{ .Chart.NewVersion }}`
