# .chartreleaser.yaml is the configuration file for chart-releaser, a CI tool
# to update Helm Charts on application release. See the documentation at
# https://github.com/edaniszewski/chart-releaser

version: v1
chart:
  name: helmv2-chart
  repo: github.com/edaniszewski/charts-test
  path: helm2
publish:
  pr:
    branch_template: testing/{{ .Chart.Name }}/{{ .Chart.NewVersion }}
release:
  strategy: minor
extras:
- path: helm2/info.txt
  updates:
  - search: text
    replace: stuff
